### ISSUE TITLE
Playback error with special characters � such as (ï Š  ’’)

### ISSUE THREAD

**Issue by bisoloc** [lrkrol/Noctifer-Music#14]
Hello,

I own this site: https://app.sets.live/?play=.%2FLivesets%2FTechno+Collection+by+sanelbestxxx%2FAlex+Flatner+-+On+Mono%EFd+%282007%29.mp3 where I post livesets. Unfortunately, it cannot work with special characters-

![image](https://github.com/lrkrol/Noctifer-Music/assets/111205812/bea1ced9-32ce-4193-a4e5-cd5f087b3f5d)

**Comment by lrkrol** [comment]
I can verify that the link you gave indeed does not play for me, either, but I'm afraid I cannot reproduce this error otherwise. When I use a file that has the special characters you mention in its filename, artist name, song name, and album name, it still [plays fine](https://music.lrk.tools/test/?play=.%2F%C3%AF%20%C5%A0%20%E2%80%99%E2%80%99.mp3) on Noctifer Music. Even adding the Unicode replacement character � itself, it [still works](https://music.lrk.tools/test/?play=.%2F%C3%AF%20%C5%A0%20%E2%80%99%E2%80%99%20%EF%BF%BD.mp3) on my machine. Do these test files play for you, too?

I suspect the special character in your file is in fact something different than the `ï` it should be, nor is it a "clean" � character. Perhaps the software you use to upload files erroneously converts some characters?

You can use e.g. this [Unicode text analyzer](https://www.fontspace.com/unicode/analyzer) to see which characters are in the file name.

**Comment by bisoloc** [comment]
Hello, it was due to my Windows FTP upload method. Thank you!
