### ISSUE TITLE
non-printable unicode characters

### ISSUE THREAD

**Issue by makato-private** [lrkrol/Noctifer-Music#8]
![Screenshot](https://user-images.githubusercontent.com/65568548/195995268-a749066b-e5d9-411e-97da-66b17a631bf7.png)

Some Characters can't be printed, which results in an Error.

**Comment by lrkrol** [comment]
From the screenshot, I cannot see what characters aren't printed. The online demo contains some cyrillic and other special characters which appear to cause no issue. Could you be more specific as to the characters that are problematic, or perhaps send me one of the files you're having issues with?

**Comment by makato-private** [comment]
Hello,

Sure, here is the link where you can download the file as .MP3 and check it yourself via Tags, or Encoding Options.

https://app.sets.live/?play=.%2FTracks%2Fexplo-172615102022%2FAgn%E8s+-+Silent+Obz.mp3

**Comment by lrkrol** [comment]
I'm afraid it's been too long since I got around to this, and now the file is no longer available for download. However, this issue might be related to #11 which I just fixed in the recent [release v0.7.3](https://github.com/lrkrol/Noctifer-Music/releases/tag/v0.7.3). Could you see if this fixes your issue, too, and if not, get me the problematic file again?
